<a href="https://colab.research.google.com/github/Sushila-Phogat/Machine-Learning-using-ML-library/blob/master/P.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create a (4 x 2) integer array and print it's attributes


In [2]:
import numpy

firstArray = numpy.empty([4,2], dtype = numpy.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[38704   613]
 [    0     0]
 [    2     0]
 [    0     0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


#Create an array of dimension (1,10) and sort it in ascending and descending order

In [59]:
import numpy as np
temp = np.arange(1,11)   
print(temp)
print(temp[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [15]:
import numpy as np
temp = np.arange(1,10)
temp.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Stack two arrays of any size horizontally and vertically

In [17]:
import numpy as np
a = np.array((1,2,3))
b = np.array((2,3,4))
print('Horizontally stacked arrays are as below:')
print(np.hstack((a,b)))
print('Vertically stacked arrays are as below:')
print(np.vstack((a,b)))

Horizontally stacked arrays are as below:
[1 2 3 2 3 4]
Vertically stacked arrays are as below:
[[1 2 3]
 [2 3 4]]


#Create two array of same size and find commom elements

In [25]:
def common_elements(a, b):
  a.sort()
  b.sort()
  i, j = 0, 0
  common = []
  while i < len(a) and j < len(b):
    if a[i] == b[j]:
      common.append(a[i])
      i += 1
      j += 1
    elif a[i] < b[j]:
      i += 1
    else:
      j += 1
  return common

print ('Common values:', ', '.join(map(str, common_elements([1, 2, 4, 8], [1, 4, 9]))))

Common values: 1, 4


#Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [73]:
import numpy as np
import random
X = np.arange(1,26)

mat = X.reshape((5,5))
random.shuffle(mat)
print(mat)

print('Maximum elements rowwise are below: ')
print(np.amax(mat, 1))
print('Minimum elements rowwise are below: ')
print(np.amin(mat,1))
mat=np.transpose(mat)
print('Maximum elements columwise are below: ')
print(np.amax(mat, 1))
print('Minimum elements columnwise are below: ')
print(np.amin(mat,1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Maximum elements rowwise are below: 
[ 5 10  5 20 25]
Minimum elements rowwise are below: 
[ 1  6  1 16 21]
Maximum elements columwise are below: 
[21 22 23 24 25]
Minimum elements columnwise are below: 
[1 2 3 4 5]


#Create an array of size 100 and compute the mean, median, standard deviation.

In [82]:
import numpy as np
mat= np.arange(1,101)
random.shuffle(mat)
mat
print(mat)
print('Mean of arrray is :' ,np.mean(mat))
print('Mean of arrray is :' ,np.median(mat))
print('Mean of arrray is :' ,np.std(mat))

[ 31  56  82  12  34  60  67  29  64   7  24  25  98  16  17  79  61  62
  83  21  41  14  96  87  91   4  89 100  33  73  88  26  19  81  35  54
   1  47  55  68  57  15  99  48  50  97  13  75  30  53  39   9  22  43
  23  95  52  69  59  93  71  11  18   3  32  37  58  63   2  74  85  45
  27  38  70  90  66  28  77  86   8  76  84  92  36  51   6  78  49  46
  20  80  10  42  44  65   5  40  72  94]
Mean of arrray is : 50.5
Mean of arrray is : 50.5
Mean of arrray is : 28.86607004772212
